### ISSUE TITLE
Check widths of data being poked into io ports

### ISSUE THREAD

**Issue by chick** [ucb-bar/chiseltest#105]
Currently one can poke a number that is too many bits for the input port.
This can lead to confusing behavior in verilator.
Treadle seems to be relatively immune to this

**Comment by schoeberl** [comment]
> On 19 Dec, 2019, at 21:10, Chick Markley <notifications@github.com> wrote:
> 
> Currently one can poke a number that is too many bits for the input port.
> This can lead to confusing behavior in verilator.
> Treadle seems to be relatively immune to this
> 
> 
Would be good if this user error could result in a runtime error (independent of tester backend).

Martin

**Comment by ekiwi** [comment]
This is checked now.
