### ISSUE TITLE
Problem with logger setup

### ISSUE THREAD

**Issue by chick** [ucb-bar/chiseltest#126]
I think the TestBuilder in ChiselScalaTestTester should be doing a makeScope to set up the logging options. Chisel stage does it but I think it's possibly too late. This is not a big deal but could cause confusing behavior for users using the logger in Chisel modules and tests. Should that be allowed or is logger only for internal and tools use?

**Comment by ekiwi** [comment]
Logging is completely broken and probably won't be fixed anytime soon.
