### ISSUE TITLE
Use firrtl to construct IOs for verilator 

### ISSUE THREAD

**Issue by sequencer** [ucb-bar/chiseltest#155]
If firrtl transform altered the top IO like https://github.com/sequencer/diplomatictester does.
The removed IO will still be elaborated to verilator API. since the IOs are set by
https://github.com/ucb-bar/chisel-testers2/blob/db85e6fcb5ce2d8397ea0d9ed1745cdd5b7b9e35/src/main/scala/chiseltest/legacy/backends/verilator/Utils.scala#L35
This will help `chisel.aop` work in tester2 too.

**Comment by sequencer** [comment]
#156 experimentally solved this.

**Comment by ekiwi** [comment]
Feel free to open a PR with a failing test case if you are still interested in this.
