### ISSUE TITLE
any way seperate  compile and simulation

### ISSUE THREAD

**Issue by pxs7** [ucb-bar/chiseltest#613]
in some testbench,  just simulation args need be change to run different case， but just need compile once, is there any way seprate chiseltest compile and simulation

**Comment by ekiwi** [comment]
Currently this is not supported, but this feature has been requested in the past. If you want to make it more likely that this will eventually be implemented it would be great if you could write down a description of your use-case. Just tell us a bit about your design, how many tests you think could use the same simulation binary and how much time you estimate you could save.

**Comment by pxs7** [comment]
thanks， current no many case， just thinking out the simulating pross of vcs， which seprate compile and simulating
