### ISSUE TITLE
Generate waveform file in real-time

### ISSUE THREAD

**Issue by liuxd17thu** [ucb-bar/chiseltest#660]
I'm working on a big chisel project, and the simulation runs with a large & uncertain cycle count (typically ~3000 cycles) slowly.
Now the problem is that, when the simulation stops because of OOM / errors in simulation / manually aborting, the vcd waveform file is totally blank, instead of showing me things which have been simulated already.
Is there a way to update the waveform file in real time (in other words, by cycle), and what should I adjust in the test?
```scala
 test(new Foo()).withAnnotations(Seq(WriteVcdAnnotation)){ c =>
  ...
}
```

**Comment by ekiwi** [comment]
Treadle, the default simulator for chiseltest, has a problematic architecture where it will only write the VCD at the end of the test. I think the easiest fix for your problem would be to switch to using Verilator.

Just add the `VerilatorBackendAnnotation` like so:

```.scala
test(new Foo()).withAnnotations(Seq(WriteVcdAnnotation, VerilatorBackendAnnotation)){ c =>
  ...
}
```

Please let me know if that works for you!
