### ISSUE TITLE
assertion failed: The Chisel compiler plugin is now required for compiling Chisel code

### ISSUE THREAD

**Issue by EricFrodo** [ucb-bar/chiseltest#695]
excuse, I have been confused for a day
I have add the compilerPlugin in sbt why is  still the problem?
my build.sbt is here
![image](https://github.com/ucb-bar/chiseltest/assets/37012275/7bd6282c-63c2-4046-abf0-fa9de959da35)

![image](https://github.com/ucb-bar/chiseltest/assets/37012275/ade8af88-23eb-4b44-bf41-017b6b7a3331)
![image](https://github.com/ucb-bar/chiseltest/assets/37012275/a4336da8-e50d-4336-8682-01c559c5ebc8)

**Comment by ekiwi** [comment]
Did you manage to get it working?
