### ISSUE TITLE
AXI4RAM test failed on chiseltest 5.0.2

### ISSUE THREAD

**Issue by SpinEch0** [ucb-bar/chiseltest#708]
Hi all,
below is my test code, it can run well on chisel 3.6 with chiseltest 0.6.2. but failed on chisel 6.0 with chiseltest 5.0.2.
Kevin on chisel-user google group replies me that it is a chiseltest bug.

 12                                                                                                                                                                                        
 13 class AXI4SlaveRAM(implicit p: Parameters) extends LazyModule {                                                                                                                        
 14   val ram = LazyModule(new AXI4RAM(AddressSet(0x0, 0x3ff)))                                                                                                                            
 15   val axi_m_param = AXI4MasterParameters("myaximaster")                                                                                                                                
 16   val axi_m_port = AXI4MasterPortParameters(Seq(axi_m_param))                                                                                                                          
 17   val axi_master = AXI4MasterNode(Seq(axi_m_port))                                                                                                                                      
 18   val ios = InModuleBody(axi_master.makeIOs())                                                                                                                                          
 19                                                                                                                                                                                        
 20   ram.node := AXI4Buffer() := axi_master                                                                                                                                                
 21                                                                                                                                                                                        
 22   lazy val module = new Impl                                                                                                                                                            
 23   class Impl extends LazyModuleImp(this) {                                                                                                                                              
 24     val io = ios.head                                                                                                                                                                  
 25   }                                                                                                                                                                                    
 26 }                                                                                                                                                                                      
 27                                                                                                                                                                                        
 28 class AXI4RAMTest extends AnyFlatSpec with ChiselScalatestTester {                                                                                                                      
 29   behavior of "AXI4RAM"                                                                                                                                                                
 30                                                                                                                                                                                        
 31   it should "perform axi rw operations correctly" in {                                                                                                                                  
 32     implicit val p = new BaseConfig                                                                                                                                                    
 33     val axiram = LazyModule(new AXI4SlaveRAM())                                                                                                                                        
 34     test (axiram.module) { dut =>            

the error log is:

`
AXI4RAM
- should perform axi rw operations correctly *** FAILED ***
  scala.NotImplementedError: TODO: convert SRAMAnnotation(ComponentName(mem,ModuleName(AXI4RAM,CircuitName(AXI4SlaveRAM))),8,mem,32,256,mem,8)
  at chiseltest.simulator.ChiselBridge$.convert(ChiselBridge.scala:151)
  at chiseltest.simulator.ChiselBridge$.$anonfun$annosToState$2(ChiselBridge.scala:93)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.collection.immutable.List.flatMap(List.scala:79)
  at chiseltest.simulator.ChiselBridge$.annosToState(ChiselBridge.scala:93)
  at chiseltest.simulator.ChiselBridge$.elaborate(ChiselBridge.scala:73)
  at chiseltest.simulator.Compiler$.elaborate(Compiler.scala:19)
  at chiseltest.internal.BackendExecutive$.start(BackendExecutive.scala:23)
  at chiseltest.defaults.package$.createDefaultTester(defaults.scala:25)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:32)
  ...
`

**Comment by kammoh** [comment]
Hi,
Could you please give the latest `6.0-SNAPSHOT` a try? #705 should probably have resolved this issue.
