### ISSUE TITLE
Bitwuzla has changed it's command line argument format

### ISSUE THREAD

**Issue by Gallagator** [ucb-bar/chiseltest#716]
After trying to see why my bitwuzla tests were failing, I noticed it wasn't parsing the command line arguments properly.
The arguments in question are here: https://github.com/ucb-bar/chiseltest/blob/main/src/main/scala/chiseltest/formal/backends/smt/SMTLibSolver.scala#L37

`--incremental` needs to be removed according to this: 
https://github.com/bitwuzla/bitwuzla/blob/bed6d6ed270ef94c3f2db8f03c892deec25c2a8d/NEWS.md?plain=1#L209

`smt2` is now specified as `--lang smt2` - see: https://github.com/bitwuzla/bitwuzla/blob/bed6d6ed270ef94c3f2db8f03c892deec25c2a8d/NEWS.md?plain=1#L68

Should we update the command line options along with the CI?

**Comment by ekiwi** [comment]
> Should we update the command line options along with the CI?

Ideally we would support both the old and the new arguments. It is annoying, but we might have to do one of two things:
1. call `bitwuzla --version`, parse the string to determine which options to use
2. use the new options first, if bitwuzla returns an error, use the old options
